version: "3.9"
services:
    haproxy:
        image: haproxytech/haproxy-debian:2.8
        container_name: haproxy
        volumes:
            - ./config:/usr/local/etc/haproxy:rw
        network_mode: host
        user: root
        restart: always
        logging:
          driver: json-file
          options:
            max-file: 3
            max-size: 100m
